title: The Modding Bungalo
description: The modding bungalo wiki for guides on their lists as well as other modding related stuff
theme: just-the-docs

url: https://stefangouldson.github.io/just-the-docs-template

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
